version: '3.8'

services:

  db-finan:
    build: ./db/
    # restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - '3306:3306'
    # volumes:
    #   - msqls_data:/var/lib/mysql/data

  flask-api:
    build: ./Flask/
    # volumes:
    #   - .:/app
    ports:
      - '5000:5000'
    # command: python3 app.py
    depends_on:
      - db-finan
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOSNAME: db-finan # nome do container que está o banco

  # volumes:
  #   msqls_data:
